### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Austinove** [creativetimofficial/bootstrap-vue-argon-dashboard#9]
I have tried to npm install but it fails on node-sass

**Comment by GreMaory** [comment]
For me `npm install` error is solved by `yarn install`.
I hope it can helps.

**Comment by anaelleltd** [comment]
I have the same issue with node-sass when I run yarn serve.
Even after installing node-sass globally, I still get an error, this time with node-gyp. 🤷🏿‍♀️

Edit: 
**WORKAROUND option**

1. From argon dashboard folder, open CLI and run $yarn install
2. Add sass with $yarn add -D sass (adding node-sass will cause a version error)
3. Run $yarn serve

**Comment by tinybug-m** [comment]
god it's a cancer

**Comment by tinybug-m** [comment]
same here

**Comment by ChenShiChao** [comment]
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\super.chen\\Prj\\bootstrap-vue-argon-dashboard\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.15.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\super.chen\\Prj\\bootstrap-vue-argon-dashboard\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\super.chen\Prj\bootstrap-vue-argon-dashboard\node_modules\node-sass
gyp ERR! node -v v16.15.1
gyp ERR! node-gyp -v v3.8.0

**Comment by sreekarsamineni** [comment]
This worked for me.

`yarn remove node-sass`
`yarn add sass`
or
`npm remove node-sass`
`npm add sass`

Then, 
`yarn install `
or 
`npm install`
